# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'BaiSiBuDeJie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiSiBuDeJie
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'iCarousel'
    pod 'WMPageController'
    pod 'MWPhotoBrowser'
    pod 'FDFullscreenPopGesture'
end
